sudo: required
dist: xenial
language: csharp
mono: none
dotnet: 2.2.105
if: tag IS blank
services:
  - docker
before_install:
  - git fetch --unshallow || true
  - dotnet tool install -g gitversion.tool
  - 
script:
  - ./build.sh ci